import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Myprovider } from "@/context/Mycontext.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Myprovider>
          <Navbar></Navbar>
          {children}
        </Myprovider>
      </body>
    </html>
  );
}
